import { Router } from 'express';
import authRouter from './auth.js';
import healthRouter from './health.js';
import usersRouter from './users.js';
import studentsRouter from './students.js';
import staffRouter from './staff.js';
import classesRouter from './classes.js';
import subjectsRouter from './subjects.js';
import attendanceRouter from './attendance.js';
import gradesRouter from './grades.js';
import feesRouter from './fees.js';
import announcementsRouter from './announcements.js';
import timetableRouter from './timetable.js';
import uploadsRouter from './uploads.js';
import admissionsRouter from './admissions.js';
import libraryRouter from './library.js';
import medicalRouter from './medical.js';
import documentsRouter from './documents.js';
import parentsRouter from './parents.js';
import notificationsRouter from './notifications.js';
import assignmentsRouter from './assignments.js';
import messagingRouter from './messaging.js';
import academicsRouter from './academics.js';
import visitorsRouter from './visitors.js';
import transportRouter from './transport.js';
import hostelsRouter from './hostels.js';
import payrollRouter from './payroll.js';
import elearningRouter from './elearning.js';
import alumniRouter from './alumniRoutes.js';

const router = Router();

// Mount API routes
router.use('/auth', authRouter);
router.use('/health', healthRouter);
router.use('/users', usersRouter);
router.use('/students', studentsRouter);
router.use('/staff', staffRouter);
router.use('/classes', classesRouter);
router.use('/subjects', subjectsRouter);
router.use('/attendance', attendanceRouter);
router.use('/grades', gradesRouter);
router.use('/fees', feesRouter);
router.use('/announcements', announcementsRouter);
router.use('/timetable', timetableRouter);
router.use('/uploads', uploadsRouter);
router.use('/admissions', admissionsRouter);
router.use('/library', libraryRouter);
router.use('/medical', medicalRouter);
router.use('/documents', documentsRouter);
router.use('/parents', parentsRouter);
router.use('/notifications', notificationsRouter);
router.use('/assignments', assignmentsRouter);
router.use('/messages', messagingRouter);
router.use('/academics', academicsRouter);
router.use('/visitors', visitorsRouter);
router.use('/transport', transportRouter);
router.use('/hostels', hostelsRouter);
router.use('/payroll', payrollRouter);
router.use('/elearning', elearningRouter);
router.use('/alumni', alumniRouter);

export default router;

